services:
  backend:
    build:
      context: .
      dockerfile: docker/dockerfiles/Dockerfile
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:////app/db/hacktrent.db  # Updated for SQLite
  
    networks:
      - app_network
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    env_file:
      - .env

networks:
  app_network:
    driver: bridge

 
